### ISSUE TITLE
Faster hexoid

### ISSUE THREAD

**Issue by aquapi** [lukeed/hexoid#6]
Try this implementation

```ts
/**
 * Create a fast random ID generator that uses `Math.random()`
 */
export function randomizer(len: number, base: number = 16): () => string {
    // The hex map for appending
    const hexSize = base * base;
    const hexMap = new Array<string>(hexSize);
    for (let i = 0; i < hexSize; ++i) hexMap[i] = (i + hexSize).toString(base);

    // hex string len
    const hexLen = hexMap[0].length;
    if (len < hexLen) throw new Error(`Hex map length (${hexLen}) is larger than requested length ${len}`);

    // Reset the store
    // eslint-disable-next-line
    const exceeded = len % hexLen;

    // eslint-disable-next-line
    return Function('h', `'use strict';let s;let j;function r(){s='';j=1;for(let i=0;i<${((len / hexLen) | 0) - 1};++i)s+=h[${hexSize}*Math.random()|0];${exceeded === 0 ? '' : `s+=h[${hexSize}*Math.random()|0].substring(0,${exceeded});`}};r();return ()=>{if(j===${hexSize}){r();return s+h[0];};return s+h[j++];}`)(hexMap);
}

**Comment by bompus** [comment]
I was curious, and benchmarked this myself, using a length of 21 for both, and the provided random function was indeed faster for me on both node and bun ( ~ 1.08x faster ) with 5000 samples. However, the minified size is exactly 2.00x larger.

Removing the error check line, I could get it down to 504 bytes, where hexoid is 252 bytes with the same minifier.

Interestingly, in bun at 50 samples, the provided functoin is MUCH slower ( random 20k op/s vs hexoid 1700k op/s ). In node, they are closer at 50 samples ( random 1482k op/s vs hexid 3033k op/s ), but hexoid still takes the win. Perhaps I'm not familiar enough with bun/jsc benchmarking intricacies, ( I didn't use optimizeNextInvocation? ). I used cronometro for my testing.

The 50 sample benchmark might need more testing, since hexoid initializes an array on import, and random peforms all initialization within the init function, which is likely the difference here.

Just my thoughts, hope my side research was helpful.

**Comment by aquapi** [comment]
@bompus I use `mitata` can you try that instead?
As I know `mitata` is the most accurate single thread benchmarking tool rn.
